/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Action LevelUp bonuses": "行动升级加成",
    "Action Statistics": "行动统计",
    "Action Effects": "行动效果",
    "Actions": "行动",
    "Attributes": "属性",
    "Coins": "金币",
    "Energy": "能量",
    "Hide": "隐藏",
    "Learning Rate": "学习速率",
    "Level": "等级",
    "Level:": "等级:",
    "Next unlock at level": "下一个解锁于等级",
    "Jobs": "工作",
    "Push Up": "俯卧撑",
    "Resources": "资源",
    "Show hidden": "显示隐藏项",
    "Training": "训练",
    "Walking": "散步",
    "XP:": "经验值:",
    "Automation": "自动化",
    "Base": "基础",
    "Export as text": "导出存档字符串",
    "Export as file": "导出为文件",
    "Export:": "导出:",
    "Import:": "导入:",
    "Import text": "导入文本",
    "Import file": "导入文件",
    "Learn ETA's": "学习ETA",
    "Stamina": "体力",
    "Skills": "技能",
    "Skill points available:": "可用技能点:",
    "Strength": "力量",
    "Time spent:": "耗时:",
    "Vitality": "活力",
    "XP earned:": "获取的经验值:",
    "Press space bar to start a drag.\n  When dragging you can use the arrow keys to move the item around and escape to cancel.\n  Some screen readers may require you to be in focus mode or to use your pass through key": "按空格键开始拖动。当拖动时，您可以使用方向键来移动项目，并使用escape来取消。\n某些屏幕阅读器可能需要您处于对焦模式或使用直通键",
    "Perform some walking exercises to improve your stamina": "进行一些散步运动，以提高你的体力",
    "Perform some simple physical exercises to become stronger and unlock better physical jobs options": "做一些简单的体育锻炼，变得更强壮，并解锁更好的体力工作选项",
    "Press to buy.": "点击购买。",
    "Health cap.": "生命值上限。",
    "Energy cap.": "能量上限。",
    "Coins cap.": "金币上限。",
    "Stop": "停止",
    "Treasurer": "宝藏",
    "Cost:": "成本:",
    "Effects:": "效果:",
    "Energizer": "增能器",
    "Health": "生命值",
    "Oak Heart": "橡树之心",
    "Scholar": "学者",
    "Skill Points": "技能点",
    "Increase your stamina": "提高你的体力",
    "Increase your learning ability": "提高你的学习能力",
    "Increase your HP regen": "提高你的生命值回复",
    "Increase your coins cap": "提高你的金币上限",
    "Recovery": "回复",
    "Do some exercises in local gym to improve your body": "在当地的健身房做一些运动来改善你的身体",
    "to your learning speed": "到你的学习速度",
    "Focus providing x": "专注提供 x",
    "Train Endurance": "训练耐力",
    "Your focus is capped at": "你的专注上限是",
    "), providing": "), 提供",
    "% intensity": "% 强度",
    "Allows you for planning your actions. Unlocks actions list": "允许你计划你的行动。解锁行动列表",
    "Beggar": "乞丐",
    "Bag": "袋子",
    "Begging Efficiency": "乞讨效率",
    "Charisma": "魅力",
    "Clean Stable": "清理马厩",
    "Clean Stables to earn some gold": "清理马厩赚取一些金币",
    "Cost: (x": "成本: (x",
    "Hat": "帽子",
    "Items": "物品",
    "Max": "最大",
    "Notebook": "笔记本",
    "Purchase": "购买",
    "Primary attribute speeds up action, increasing both production and consumption": "主属性可以加速行动，提高生产和消耗",
    "Primary Attribute:": "主属性:",
    "Purchase a bag to store more coins": "购买袋子可以储存更多的金币",
    "Purchase a hat to collect more coins from begging and have a bit more place to store them": "购买一顶帽子可以从乞讨中收集更多的金币，并且有更多的地方可以储存它们",
    "Purchase X:": "购买 X:",
    "Repair Slippers": "修理拖鞋",
    "Rest in Tavern": "在酒馆休息",
    "Shop": "商店",
    "Upgrades": "升级",
    "Walking Learning Rate": "散步学习速率",
    "Wander the city streets, hoping for someone's help": "漫步在城市的街道上，希望有人能帮助你",
    "Your slippers are old, but better than nothing. If you repair it, it could make you feel more comfortable and warm": "你的拖鞋旧了，但总比没有好。如果你修复它，它会让你感觉更舒适和温暖",
    "Pay some gold to rest in tavern": "花点钱在酒馆里休息",
    "Focus": "专注",
    "Multiplier": "乘数",
    "Never": "不满足",
    "You are running this action for": "你当前的行动持续了",
    "Total time played:": "总计游戏时长:",
    "Actions XP Earned:": "获得的行动经验:",
    "Actions Time Spent:": "花费的行动时间:",
    "Actions Unlocked:": "解锁的行动:",
    "Mage Level:": "法师等级:",
    "Attributes unlocks": "属性解锁",
    "Actions unlocks": "行动解锁",
    "Patience": "耐心",
    "Upcoming Unlocks Requirements": "即将解锁条件",
    "View statistics": "查看统计",
    "View unlocks": "查看解锁",
    "You were offline": "你离线了",
    "Diary": "日记",
    "Use your diary to write up what you have learned everyday. Improves learning rate": "用你的日记本记下你每天学到的东西。提高学习速率",
    "Create New": "新建",
    "Current list:": "当前列表:",
    "Gossip": "闲聊",
    "Lists automation enabled": "启用自动化列表",
    "Pick list": "选择列表",
    "Switch lists interval:": "列表切换时间间隔:",
    "Rules Condition:": "规则条件:",
    "Priority:": "优先级:",
    "Name": "名称",
    "Create": "创建",
    "Create & Close": "创建 & 关闭",
    "Click on actions or drag & drop them to add": "单击行动或拖放它们来添加",
    "Cancel": "取消",
    "Average Resources per second": "每秒平均资源数",
    "Average Effects per second": "每秒平均效果",
    "Autotrigger rules:": "自动触发规则：",
    "Add rule (AND)": "添加规则（且）",
    "Street Musician": "街头音乐家",
    "Perform melodies for passersby and earn some coins through the power of music": "为路人演奏旋律，通过音乐的力量赚取一些金币",
    "Save & Close": "保存 & 关闭",
    "seconds": "秒",
    "Spend some time communicating with people about news and other things. Improves your charisma": "花点时间和别人交流新闻和其他事情。提高你的魅力",
    "You are over an area that cannot be dropped on": "你所处的区域不能被放到",
    "You can set more complex matching conditions, like (1 AND 2) OR 3, where numbers are numbers of your rules": "您可以设置更复杂的匹配条件，如（1 和 2） 或 3，其中数字是您的规则的数字",
    "Edit List": "编辑列表",
    "Delete List": "删除列表",
    "Run List": "运行列表",
    "Bargaining": "讨价还价",
    "Charisma improves your communication skills and interaction with other people and decrease shop prices. Higher level unlocks more social activities": "魅力可以提高你的沟通技巧和与他人的互动，降低商店价格。等级越高可以开启更多社交活动",
    "Bargaining attribute slightly increase your coins income from all sources": "讨价还价属性稍微增加你所有来源的金币收入",
    "Consumption": "消耗",
    "Improves your health regeneration": "提高你的生命回复",
    "Income": "收入",
    "Mage": "法师",
    "Patience impacts on your ability on focusing on routine tasks and increasing learning speed. Higher level unlocks more gathering and routine activities": "耐心会影响你专注于日常任务和提高学习速度的能力。等级越高可以解锁更多的聚会和日常活动",
    "Stamina impacts on how fast you can restore your energy": "体力会影响恢复能量的速度",
    "Strength impacts on physical activities efficiency and increase energy cap. Higher level unlocks more physical activities": "力量影响体力活动效率，增加能量上限。等级越高，解锁的体力活动越多",
    "Vitality improves your health maximum": "活力可以提升生命值上限",
    "Book of Math": "数学之书",
    "Book of Motivation": "励志之书",
    "Purchase a book that you can read when you have time. Maybe you will find something useful there": "买一本你有时间可以看的书。也许你会在那里找到有用的东西",
    "Allows you doing some primitive math exercises to train your brain in calculating coins": "让你做一些原始的数学练习来训练你的大脑通过计算金币",
    "Read book of Motivation": "阅读励志之书",
    "Read book of motivation, containing some useful advices regarding self-development": "阅读《励志之书》，其中包含了一些关于自我发展的有用建议",
    "Backpack": "背包",
    "Panpipe": "牧羊神之笛",
    "Shovel": "铲子",
    "Primitive tool to increase your working at stable efficiency": "原始的工具，以稳定的效率提高您的工作",
    "Unlocks inventory and items": "锁库存和物品",
    "Perform some primitive show to improve begging efficiency": "进行一些原始的表演来提高乞讨效率",
    "Better Urns": "更好的瓮",
    "Clean Stable Efficiency": "清理马厩效率",
    "Inventory": "库存",
    "Entrance To Library": "进入图书馆",
    "Living Space": "生活空间",
    "Invest some coins you have earned into your own development": "把赚来的钱投入到自己的发展中",
    "Property": "地产",
    "Tent": "帐篷",
    "Tools": "工具",
    "Urns storage bonus": "瓮储存加成",
    "Purchase your very first living property. Not really comfortable, but better than nothing": "购买你的第一处房产。不是很舒服，但聊胜于无",
    "Purchase better urns to increase their capacity": "购买更好的瓮来增加它们的容量",
    "Purchase better tools, improve your performance at any job. Increase coins income": "购买更好的工具，提高你在任何工作中的表现。增加金币收入",
    "Balance:": "平衡:",
    "Effects on usage:": "使用效果:",
    "Consumption Cooldown:": "消耗冷却时间:",
    "Consumed amount:": "消耗数量:",
    "Autosell rules:": "自动出售规则:",
    "Autoconsumption rules:": "自动消耗规则:",
    "Berry": "浆果",
    "Cart": "推车",
    "Coins Earning Bonus": "赚取金币加成",
    "Consumable": "消耗品",
    "Easy and convenient cart for better transportation of gathered things. Improves gathering efficiency": "简单方便的推车，更好地运输收集的东西。提高采集效率",
    "Elementary place where you can sleep. Improves rest efficiency": "可以睡觉的初级场所。提高休息效率",
    "Furniture": "家具",
    "furniture": "家具",
    "Gather Berries": "采集浆果",
    "gathering": "采集",
    "Gathering": "采集",
    "Gathering Efficiency": "采集效率",
    "Left click to select": "左键点击以选择",
    "Place some table where you can sit and put down notes or read books.": "放一些桌子，你可以坐下来写笔记或看书。",
    "Remove": "移除",
    "Rest Efficiency": "休息效率",
    "Right click to consume": "右键点击以消耗",
    "Sell": "出售",
    "Sell max (x": "出售最大 (x",
    "Sell price:": "出售价格:",
    "Sleeping Bag": "睡袋",
    "Small urn to store more gold": "小瓮储存更多的金币",
    "Space:": "空间:",
    "Spend some time walking in nearby forest and collecting berries": "花点时间在附近的森林里散步，收集浆果",
    "Table": "桌子",
    "Train Math": "训练数学",
    "Urn": "瓮",
    "Train you brain to calculate coins better. Increase coins income": "训练你的大脑更好地计算金币。增加金币收入",
    ". Hold Shift to by max": "．按住Shift键以购买最大",
    "Bread": "面包",
    "Press to buy x": "按下购买 x",
    "Wood": "木头",
    "Consumable Cooldown Reduction": "减少消耗品的冷却时间",
    "Decrease cooldown of consumable items usage": "减少消耗性物品的冷却时间",
    "Increase amount of items you can sell": "增加你可以出售的物品数量",
    "Merchant": "商人",
    "Metabolism": "新陈代谢",
    "Shop Max Stock": "商店最大存货",
    "Stock Renew Rate": "存货更新率",
    "Rest at home": "在家休息",
    "Stay at your sweet home to heal and recover": "呆在你温馨的家里，好好疗伤",
    "Anatomy Book": "解剖学之书",
    "Glasses": "眼镜",
    "Knowledge": "知识",
    "Yoga Manual": "瑜伽手册",
    "Vocabulary": "词汇表",
    "Read Books Efficiency": "读书效率",
    "Purchase yoga manual to train your patience and improve gathering and routine tasks performance": "购买瑜伽手册来训练你的耐心，提高采集和日常任务的表现",
    "Purchase glasses to read better and gather knowledge faster": "购买眼镜，以便更好地阅读和更快地收集知识",
    "Purchase book that can improve your understanding of your body": "购买可以提高你对自己身体结构了解的书籍",
    "Most of books are written in old and obscure languages. Purchase vocabulary and start learning languages to make your book reading more efficient": "大多数书都是用古老而晦涩的语言写的。购买词汇表，开始学习语言，让你的读书更有效率",
    "book": "书籍",
    "activity": "活动",
    "Activities": "活动",
    "Brighten your living space for more convenient reading, writing and learning": "照亮你的生活空间，更方便阅读、写作和学习",
    "Oil Lamp": "油灯",
    "Knowledge cap.": "知识上限.",
    "Place some small wooden furniture to place books and notes.": "放一些小的木制家具来放书和笔记。",
    "Small Book Case": "小书柜",
    "Read Books": "读书",
    "Read books to find new information and increase your knowledge": "读书可以发现新的信息，增加你的知识",
    "Action Efficiency": "行动效率",
    "Highbrow": "知识分子",
    "Increase your knowledge capacity and regeneration": "提高你的知识能力和再生能力",
    "Cot": "床",
    "Old and smelly, but much better than your sleep bag": "又旧又臭，但比你的睡袋好多了",
    "Physical Training Learning": "体能训练及学习",
    "Provide some elementary inventory to improve physical training efficiency, like Training Endurance": "提供一些基本的库存，以提高体能训练效率，如训练耐力",
    "Workout Bench": "健身椅",
    "Use it for your daily yoga practices, increasing yoga XP rate": "将它用于你的日常瑜伽练习，增加瑜伽经验值",
    "Yoga Carpet": "瑜伽毯",
    "Yoga Learning Rate": "瑜伽学习速率",
    "Yoga Practice": "瑜伽练习",
    "Practice yoga to train your patience and stamina. Unlocks new activities requiring more patience.": "练习瑜伽可以锻炼你的耐心和耐力。解锁需要更多耐心的新活动。",
    "Clean your house, organize things to free more space for coins storage": "打扫你的房子，整理东西，腾出更多的空间来存放金币",
    "Coins cap multiplier": "金币上限乘数",
    "Home Errands": "家庭杂务",
    "Learn Anatomy": "学习解剖学",
    "Memory": "记忆",
    "Lear anatomy to better understand your body and improve your health regeneration": "学习解剖学，以更好地了解你的身体和提高你的生命值再生",
    "Walking in Forest": "林中漫步",
    "Fly Mushroom": "飞蝇蘑菇",
    "More dangerous activity, but searching for plants in less accessible places can pay off": "更危险的活动，但在不易接近的地方寻找植物是值得的",
    "Herbs Handbook": "草药手册",
    "Its barely a good weapon, but it can be used to cut things you found more efficiently": "它算不上是一件好武器，但它可以用来更有效地切割你发现的东西",
    "Knife": "刀",
    "Learn new herbs and their effects": "学习新的草药和它们的作用",
    "Cardio Training": "有氧运动训练",
    "Crafting Courses": "手工艺课程",
    "Crafting Slots": "制作槽位",
    "Finally, you feel the power in your hands. But still, you feel like you need to train more": "最后，你感觉到了手中的力量。但是，你仍然觉得你需要更多的训练",
    "Improves your knowledge capacity": "提高你的知识能力",
    "Manual Labor Efficiency": "体力劳动效率",
    "Patrol": "巡逻",
    "Personal Gym": "私人健身房",
    "Protect streets from hooligans and robbers. Its risky and hard job, but its well paid": "保护街道免受流氓和强盗的侵害。这是一份有风险且艰苦的工作，但报酬丰厚",
    "Provide better inventory to improve physical training efficiency": "提供更好的库存，提高体能训练效率",
    "Provides you with some place and instruments to repair your tools, increasing your manual-labor actions efficiency": "为你提供一些地方和工具来修理你的工具，提高你的体力劳动效率",
    "Tools Workshop": "工具作坊",
    "Unlocks crafting and materials processing": "解锁制作和材料加工",
    "Woodcutting": "伐木",
    "XP": "经验值",
    "Rules": "规则",
    "You haven't unlocked any automations yet :=(": "您还没有解锁任何自动化 :=(",
    "spell": "法术",
    "Action Level": "行动等级",
    "Action Lists Automations": "行动列表自动化",
    "Add Rule": "添加规则",
    "Alchemy Effort": "炼金术的努力",
    "Alchemy Slots": "炼金术槽",
    "Aloe Vera": "芦荟精华素",
    "Autospell rules:": "Autospell规则:",
    "Better Stashes": "更好的能力",
    "Candle Holder": "烛台",
    "Cooldown:": "冷却时间:",
    "Crafting Effort": "制作工作",
    "Don't worry, you'll unlock them pretty soon": "别担心，你很快就会打开的",
    "Edit": "编辑",
    "Effects during cast:": "施法期间的效果：",
    "Effort": "努力",
    "Exact": "精确",
    "Ginseng": "人参",
    "Guild Points": "公会点数",
    "Guild Reputation": "协会的声誉",
    "Handbook": "手册",
    "Improve your learning capabilities using magic": "用魔法提高你的学习能力",
    "Increase your mana regen and capacity": "增加你的法力回复和容量",
    "Invalid": "无效的",
    "Lear ancient languages to increase book reading related XP": "学习古代语言，增加书籍阅读相关XP",
    "Learn how to improve your spells by analyzing your mistakes and earning experience. Spells now can be leveled": "学习如何通过分析错误和积累经验来提高你的法术。法术现在可以升级了",
    "Learn Languages": "学习语言",
    "Learn some basic illusion spells.": "学习一些基本的幻术法术。",
    "Learn some basic restoration spells.": "学习一些基本的恢复法术。",
    "Lesser Illusion": "低级幻境",
    "Lesser Restoration": "低级恢复",
    "Made of mana and glass": "由法力和玻璃制成",
    "magic": "魔法",
    "Magic Ability": "魔法能力",
    "Magic garden is told to be planted by some wizard. The wizard was murdered, but his garden keeps growing, providing variety of precious herbs": "魔法花园据说是由某个巫师种植的。巫师被谋杀了，但他的花园不断生长，提供各种珍贵的草药",
    "Magic Insight": "魔法洞见",
    "Magic Orb": "魔法球",
    "magical": "魔法",
    "Mana": "法力",
    "Mana cap.": "法力上限。",
    "Mana Orb": "法力球",
    "Materials": "材料",
    "Meditate": "冥想",
    "Nightshade": "龙葵",
    "percentage": "百分比",
    "Percentage": "百分比",
    "Place magic candle holder to further improve mana power": "放置魔法烛台以进一步提高法力",
    "Place magic orb to improve mana regeneration": "放置魔法球提高法力回复",
    "Plantation Slots": "种植槽",
    "Purchase better stashes to increase coins capacity even more": "购买更好的藏匿处，以增加更多的金币容量",
    "Purchase Land": "购买土地",
    "Purchase some land for even more space": "购买一些土地以获得更大的空间",
    "Read Books Learning Rate": "阅读书籍学习速度",
    "Resource Amount": "资源的数量",
    "Resource Balance": "资源平衡",
    "Running Action": "运行操作",
    "Running Action With Tag": "带标签运行行动",
    "Searching in Magic Garden": "在魔法花园寻找",
    "Sorcer": "魔法师",
    "Spell Automations": "法术自动化",
    "Spell duration:": "法术持续时间:",
    "Spellbook": "法术书",
    "Spellcraft": "法术制作",
    "spiritual": "精神",
    "Use meditative practices to improve your mental abilities": "使用冥想练习来提高你的思维能力",
    "Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.": "使用上下键选择选项，按Enter键选择当前关注的选项，按Escape键退出菜单，按Tab键选择该选项并退出菜单。",
    "Use your magic capabilities to understand world better": "用你的魔法能力去更好的理解这个世界",
    "(Based on max level)": "（按最高等级计算）",
    "A Mysterious Stranger": "神秘的陌生人",
    "Cursed Mirror": "被诅咒的镜子",
    "Enchant your body for faster recovery": "为你的身体施魔法，以便更快地恢复",
    "events": "事件",
    "Heal yourself using magic": "使用魔法治疗自己",
    "Hide maxed": "隐藏已最大",
    "Improves your mana regeneration": "提高你的法力回复",
    "Improves your restoration magic efficiency": "提高你的恢复魔法效率",
    "Less Magic Recovery": "减少魔法恢复",
    "Less Magic Regeneration": "减少魔法再生",
    "Price reduction": "降价",
    "restoration": "恢复",
    "Restoration Magic Circle": "恢复魔法阵",
    "Restoration Magic Efficiency": "恢复魔法效率",
    "restoration_magic": "恢复魔法",
    "Show all": "显示所有",
    "A Dispute Over a Spell": "关于一个法术的争论",
    "A Mage’s Duel": "法师的决斗",
    "A ring of fire encircles you, and a booming voice challenges you to endure its heat to prove your worth.": "一圈火围绕着你，一个响亮的声音挑战你忍受它的热量来证明你的价值。",
    "A traveling warrior challenges you to a duel, promising great rewards for your courage.": "一名旅行的战士向你挑战决斗，并承诺对你的勇气给予巨大的奖励。",
    "A wandering monk approaches, offering to teach you a secret technique in exchange for some of your wealth. Do you accept?": "一个流浪的和尚走过来，提出教你一种秘密技术，以换取你的一些财富。你接受吗？",
    "A wandering priest offers to bestow a blessing upon you, enhancing your ability to recover from wounds.": "一位流浪的牧师会给你一个祝福，增强你从伤口中恢复的能力。",
    "Accept the Duel": "接受决斗",
    "An Enchanted Fountain": "魔法喷泉",
    "Ancient Shrine": "古老的神殿",
    "Ancient Tome": "古老的典籍",
    "As you work, your hands move with unexpected precision, and ideas flow easily. Could this be a hidden talent emerging, or just a fleeting moment of clarity?": "当你工作的时候，你的手会以意想不到的精准移动，你的想法也很容易产生。这是一种隐藏的天赋，还是一闪而过的清晰？",
    "Blessing of Endurance": "忍耐的祝福",
    "Challenger's Duel": "挑战者的决斗",
    "Charmed Audience": "吸引观众",
    "Cryptic Riddle": "神秘的谜题",
    "Decline the Challenge": "拒绝挑战",
    "Endure the Flames": "忍受火焰",
    "Energy Surge": "能量涌动",
    "Event": "事件",
    "Forgotten Altar": "被遗忘的祭坛",
    "Golden Opportunity": "千载难逢",
    "Healing Springs": "治疗温泉",
    "Hidden among the trees, you find an ancient altar, etched with mysterious runes. A faint glow suggests untold power, but a voice in your mind warns of potential danger.": "隐藏在树林里，你会发现一个古老的祭坛，上面刻着神秘的符文。微弱的光芒暗示着无尽的力量，但你脑海里的声音警告着潜在的危险。",
    "Hidden Talent": "隐藏的天赋",
    "Ignore it": "忽略它",
    "Ignore the Shrine": "忽略神殿",
    "In the library, you discover an ancient tome glowing faintly on a dusty shelf. Its title is indecipherable, but you feel drawn to it.": "在图书馆里，你发现一本古老的典籍在布满灰尘的书架上微微发光。它的标题难以辨认，但你会被它吸引。",
    "Inspire the Crowd": "激励人群",
    "Join as a Mediator": "作为调解员加入",
    "Join the Duel": "加入决斗",
    "Leave It Alone": "别管它",
    "Leave the Altar": "离开祭坛",
    "Library Apparition": "图书馆的幽灵",
    "Lost Coin": "丢失的金币",
    "Magical Misfire": "魔法失败",
    "Mysterious Scroll": "神秘的卷轴",
    "Nothing happens": "什么也没发生",
    "Nurture it": "培养它",
    "Offer a Prayer": "祈祷",
    "Offer Gold": "提供金币",
    "Pay the Monk": "付钱给和尚",
    "Politely Refuse": "礼貌地拒绝",
    "Put It Back": "放回去",
    "Read the Tome": "阅读典籍",
    "Receive the Blessing": "接受祝福",
    "Recreate the Experiment": "重现实验",
    "Refuse the Offer": "拒绝支付",
    "Remain Silent": "保持沉默",
    "Retreat from the Challenge": "逃避挑战",
    "Some choices can provide different outcomes. Try it to reveal potential bonuses and risks": "有些选择可以提供不同的结果。试着揭示潜在的奖励和风险",
    "Speed Reading Bet": "速读打赌",
    "Street Performers": "街头艺人",
    "Study the Log Carefully": "仔细研究日志",
    "The event have expired. But don't worry, they repeat sometimes": "事件已过期。但别担心，他们有时会重复",
    "The Fortune Teller": "算命先生",
    "The Overactive Spellbook": "过度活跃的魔法书",
    "The Wandering Monk": "流浪的和尚",
    "The Wandering Sage": "流浪圣人",
    "Trial of the Flame": "火焰的考验",
    "Two mages are locked in a duel, their spells lighting up the night sky. They invite you to join as a mediator or a participant.": "两个法师正在决斗，他们的法术照亮了夜空。他们邀请你作为调解人或参与者加入。",
    "Unstable Experiment": "不稳定实验",
    "Watch from the Sidelines": "旁观者旁观",
    "You come across an ancient shrine, covered in moss and glowing faintly. A voice whispers in your mind, asking for a sacrifice to unlock hidden potential. What will you do?": "你路过一座古老的神殿，上面长满了青苔，微微发光。一个声音在你脑海中低语，要求你做出牺牲来释放隐藏的潜力。你会怎么做？",
    "You find an old experiment log in the library. It describes a dangerous but potentially rewarding experiment.": "你在图书馆找到一份旧的实验记录。它描述了一个危险但有潜在回报的实验。",
    "You find yourself speaking before a small crowd. They hang on your every word, and you feel their admiration growing.": "你发现自己在一小群人面前讲话。他们听着你说的每一句话，你感到他们对你的钦佩与日俱增。",
    "Fatigue": "疲劳",
    "Knowledge Exchange": "知识交流",
    "A fellow library patron challenges you to a speed reading contest. Will you accept the challenge?": "一位图书馆的老读者向你发起一场速读比赛。你会接受挑战吗？",
    "Accept and Give Your Best": "接受并做到最好",
    "Accept Out of Curiosity": "出于好奇接受",
    "Dancing Fairy": "跳舞的精灵",
    "Illusion Magic Circle": "幻术魔术圈",
    "Illusion Magic Efficiency": "幻术魔法效率",
    "illusion_magic": "幻术魔法",
    "Knowledge Gain": "知识的获得",
    "Learn some better illusion spells.": "学习一些更好的幻术法术。",
    "Learning Rate Bonus": "学习率奖励",
    "Meditation proves taxing, and you feel your energy drain away.": "冥想是很费力的，你会感到精力枯竭。",
    "Minor Illusion": "轻微的幻术",
    "Perfection Illusion": "完美的幻术",
    "Read the Scroll": "阅读卷轴",
    "Refuse the Bet": "拒绝打赌",
    "Rest": "休息",
    "Routine Learning": "日常的学习",
    "Summon illusion of dancing fairy, inspiring you while performing routine actions. Improves learning rate for all routine tasks": "召唤舞蹈精灵的幻术，在表演常规行动的同时激励你。提高所有日常任务的学习率",
    "The day wears on, and every step feels heavier than the last. The ground looks soft and inviting, while a nearby tree offers shade and calm. What will you do?": "日子一天天过去，每一步都感觉比上一步更沉重。地面看起来柔软诱人，而附近的一棵树提供了阴凉和平静。你会怎么做？",
    "The scroll contains insights that briefly enhance your studies. (+Knowledge gain for 5 minutes)": "卷轴中包含的见解可以短暂地提高你的学习等级。（增加5分钟的知识增益）",
    "The shrine accepts your offering, and you feel your muscles strengthen. (+1 Strength)": "神殿接受了你的供品，你感到你的肌肉变得强壮起来。(力量+ 1)",
    "Use magic to create illusion that you are perfect worker. Increases coins income from jobs": "使用魔法创造一种你是完美工作者的幻术。从工作中增加金币收入",
    "While browsing the library, a rolled-up scroll falls from a high shelf and lands at your feet. Its seal is broken.": "在浏览图书馆时，一个卷起来的卷轴从高高的书架上掉下来，落在你的脚下。它的封印被打破了。",
    "You enjoy the challenge and learn a lot! (+Knowledge gain for 5 minutes)": "你喜欢挑战，也能学到很多！（增加5分钟的知识增益）",
    "You hone your new skill, gaining a temporary boost to your learning speed. (+Learning speed for 5 minutes)": "你磨练了你的新技能，暂时提高了你的学习速度。（+ 5分钟学习速度）",
    "Your knowledge gain was increased": "你的知识增长了",
    "Your learning speed is increased": "你的学习速度提高了",
    "Pick it up": "捡起来",
    "Inspect further": "进一步检查",
    "A hidden snare tightens around your leg! You lose some gold in your scramble to escape.": "一个隐藏的陷阱收紧了你的腿！你在逃跑的过程中损失了一些金币。",
    "As you stroll through the forest, the sunlight catches something shiny beneath a pile of leaves. It appears to be an old, golden coin, its edges worn smooth by time. Do you take a closer look or move on?": "当你漫步在森林里时，阳光照到了一堆树叶下闪闪发光的东西。它似乎是一枚古老的金币，它的边缘被时间磨得光滑。你会仔细看还是继续看？",
    "Channel it": "引导它",
    "Resist it": "抵抗它",
    "A vibrant energy hums in the clearing before you, as though the earth itself were breathing. The air shimmers with a faint glow, and the pull of its power is undeniable. How will you respond?": "一股充满活力的能量在你面前的空地上嗡嗡作响，仿佛地球本身也在呼吸。空气中闪烁着微弱的光芒，它的力量的吸引力是不可否认的。你会如何回应？",
    "Embrace it": "拥抱它",
    "The scroll is riddled with errors, confusing your thoughts. (-Knowledge gain for 5 minutes)": "卷轴上满是错误，迷惑了你的思路。（-知识增益持续5分钟）",
    "You draw the energy into yourself, feeling strength course through your veins. (+75% energy refill)": "你把能量吸到自己身上，感觉力量流过你的血管。（+75%能量补充）",
    "Avoid the Spring": "避开泉水",
    "Drink the Water": "喝水",
    "The water fills you with vitality. (+Health regeneration for 5 minutes)": "水使你充满活力。（+生命回复持续5分钟）",
    "You discover a bubbling spring with sparkling, crystal-clear water. A sign nearby reads: \"Drink and be rejuvenated, but beware the cost.\"": "你发现了一个冒着气泡的泉水，里面的水晶莹剔透。附近的一个牌子上写着：“喝一杯，恢复活力，但要注意成本。”",
    "A clumsy patron spills their ale on your spellbook, causing sparks to fly and minor chaos in the tavern. The barkeep looks furious, and the patron looks embarrassed.": "一个笨手笨脚的顾客把他们的啤酒洒在你的魔法书上，在酒馆里引起了火花和小混乱。酒保看起来很生气，而顾客看起来很尴尬。",
    "Demand Compensation from the Patron": "向赞助人要求赔偿",
    "Engage in a mutual exchange of ideas with others, sharing insights and gaining valuable knowledge. Slightly increases your learning speed.": "与他人相互交流思想，分享见解，获得有价值的知识。稍微提高你的学习速度。",
    "Health Regeneration": "生命值再生",
    "Let It Slide": "顺其自然",
    "manual-labor": "体力劳动",
    "Spend some time working hard to get some wood": "花点时间努力弄些木头来",
    "Spilled Ale and Sparks": "洒出的啤酒和火花",
    "Use Magic to Dry the Book": "用魔法擦干书",
    "Your health regeneration was increased": "你的生命再生增加了",
    "Use the Water for Research": "把水用于研究",
    "You find a glowing fountain in the woods. The water sparkles with magical energy, and a faint humming fills the air.": "你在树林里发现了一个发光的喷泉。水闪烁着魔法能量，空气中弥漫着微弱的嗡嗡声。",
    "Energy Debuff": "能量减益",
    "Injury": "受伤",
    "Physical Training Bonus": "体能训练加成",
    "The patron refuses and spreads rumors about your temper. (-1 Charisma)": "赞助人拒绝并散播谣言说你脾气不好。（-1魅力）",
    "The stress of the bet hampers your energy recovery. (-Energy regeneration for 5 minutes)": "赌博的压力会阻碍你的精力恢复。（-能量再生5分钟）",
    "The water enhances your research, deepening your understanding. (+Knowledge gain for 15 minutes)": "水能加强你的研究，加深你的理解。（+ 15分钟的知识增益）",
    "You are injured. Your health regeneration is decreased": "你受伤了。你的生命回复降低",
    "You fill weakened. Your energy regeneration is decreased": "你虚弱了。你的能量回复减少",
    "You lose the duel but gain valuable experience. (-10% HP, +Temporary strength training bonus, +Injury)": "你输掉了决斗，但获得了宝贵的经验。（-10%生命，+临时力量训练加成，+伤害）",
    "Your learning speed for physical training is increased": "你的体能训练学习速度提高了",
    "While flipping through your spellbook in a quiet corner of the tavern, a poorly contained spell activates, filling the room with a shimmering, unstable energy. The barkeep glares at you, and the other patrons grow uneasy.": "当你在酒馆一个安静的角落翻阅法术书时，一个不太完整的法术被激活了，房间里充满了闪烁的、不稳定的能量。酒保瞪着你，其他顾客也变得不安起来。",
    "A curse emanates from the artifact, draining your health. (You got major injury)": "神器会发出诅咒，耗尽你的生命值。（你受了重伤）",
    "Apologize to the Tavern Patrons": "向酒馆的老主顾道歉",
    "Attempt to Destroy it": "试图摧毁它",
    "Cast a Counterspell": "施放反咒",
    "Flee the Scene": "逃离现场",
    "Leave it Alone": "别管它",
    "Mana Regeneration": "法力再生",
    "Take the Artifact": "拿起神器",
    "The Lost Artifact": "遗失的神器",
    "Try to Dispel the Energy": "试着驱散能量",
    "While exploring an abandoned temple, you find a glowing artifact on a pedestal. Its power is undeniable, but a strange aura surrounds it.": "在探索一座废弃的寺庙时，你在基座上发现了一件发光的神器。它的力量是不可否认的，但它周围却笼罩着一种奇怪的光环。",
    "Your efforts stabilize the energy, leaving you refreshed. (+Mana regeneration for 5 minutes)": "你的努力稳定了能量，让你精神焕发。（+法力回复5分钟）",
    "Your mana regeneration was increased": "你的法力回复增加",
    "Energized": "精力充沛",
    "The experiment succeeds, expanding your knowledge. (+1 Memory permanently)": "实验成功了，扩展了你的知识。（永久+1记忆）",
    "You lie down and let sleep take you. You wake up refreshed, energy restored. (+Energy regeneration bonus)": "你躺下，让睡眠带走你。你醒来后神清气爽，精力充沛。（+能量回复加成）",
    "Your energy income is boosted": "你的能量收入提升了",
    "The heat is too much, and you collapse from exhaustion. (-75% HP)": "天气太热了，你累倒了。（-75%生命值）",
    "A traveling merchant with a silver tongue offers you a deal. He claims his goods will make you more persuasive, for a price.": "一个能说会道的旅行商人给你提供了一笔交易。他声称他的商品会让你更有说服力，但要付出代价。",
    "At the edge of the bustling square, a merchant draped in colorful silks waves you over. His voice is silky and persuasive as he offers a deal that seems too good to be true.": "在熙熙攘攘的广场边上，一位身披彩色丝绸的商人向你招手。他的声音柔滑而有说服力，因为他提出了一个似乎好得令人难以置信的交易。",
    "Buy the Goods": "购买商品",
    "Charismatic Merchant": "魅力商人",
    "Coins Earned Bonus": "获得金币加成",
    "Knowledge Debuff": "减益魔法知识",
    "Refuse": "拒绝",
    "Take the deal": "接受协议",
    "The deal pays off handsomely! Your gold income increases for the next 5 minutes.": "这笔交易回报丰厚！你的金币收入会在接下来的5分钟内增加。",
    "The merchant’s goods grant you an air of confidence. (+1 Charisma)": "商人的货物给你一种自信的感觉。(+ 1魅力)",
    "Walk Away": "走开",
    "You destroy the artifact, and a wave of energy heals you. (+20% HP)": "你摧毁了神器，一股能量的波动治愈了你。（生命值+20%）",
    "You feel yourself dummy. Your knowledge gain is decreased": "你觉得自己很笨。你获得的知识减少了",
    "You overexert yourself and feel drained. (-Knowledge gain for 5 minutes)": "你过度劳累，感觉筋疲力尽。（-5分钟知识增益）",
    "Your coins income is boosted": "你的金币收入增加了",
    "Hard Reset Game": "硬重置",
    "The blessing backfires, leaving you slightly weakened. (-10% HP)": "祝福适得其反，让你变得有些虚弱。（-10%生命）",
    "The patron apologizes and offers you some gold.": "老板向你道歉，并给了你一些金币。",
    "As you explore the darker corners of the library, a faint apparition appears, pointing to a hidden alcove.": "当你探索图书馆的黑暗角落时，一个微弱的幽灵出现了，指向一个隐藏的凹室。",
    "Follow the Apparition": "跟随幽灵",
    "Ignore It": "忽略它",
    "Mental Training Bonus": "心理训练奖励",
    "The apparition leads you to a forgotten cache of knowledge. (+Knowledge gain for 5 minutes)": "幽灵会把你带到一个被遗忘的知识宝库。（+ 5分钟知识增益）",
    "The counterspell enhances your focus. (+Mental training speed for 5 minutes)": "反咒可以增强你的注意力。（+ 5分钟脑力训练速度）",
    "The effort of calming everyone drains you. (-Energy regeneration for 5 minutes)": "安抚所有人的努力耗尽了你的精力。（-能量回复5分钟）",
    "The spell works perfectly, restoring calm. (+Mana regeneration for 5 minutes)": "这个法术非常有效，恢复了平静。（+法力回复5分钟）",
    "The tome is full of arcane knowledge, enhancing your understanding. (+Knowledge gain for 5 minutes)": "这本书充满了奥术知识，可以增强你的理解力。（+ 5分钟知识增益）",
    "The water revitalizes your magical reserves. (+Mana regeneration for 5 minutes)": "水可以恢复你的魔法储备。(+法力再生5分钟)",
    "Your learning speed for mental training is increased": "心理训练的学习速度提高了",
    "Accept His Wisdom": "接受他的智慧",
    "Accept the Training": "接受培训",
    "An old sage approaches you, offering to share a fragment of his magical wisdom, but warns that it could be exhausting to comprehend.": "一位老圣人走近你，愿意分享他的魔法智慧的片段，但警告说，这可能是令人筋疲力尽的理解。",
    "An old warrior invites you to train with him, promising valuable insights into strength-building techniques.": "一位老战士邀请你和他一起训练，承诺对力量建设技术有价值的见解。",
    "As you explore the darker corners of the library, a faint apparition appears, pointing to a hidden alcove.": "当你探索图书馆的黑暗角落时，一个微弱的幽灵出现了，指向一个隐藏的凹室。",
    "Ask for Practical Guidance": "请求实践指导",
    "Decline the Offer": "拒绝邀约",
    "Politely Decline": "婉言拒绝了",
    "The warrior’s advice sharpens your focus. (+Strength training speed for 5 minutes)": "勇士的建议使你的注意力更加集中。（+ 5分钟力量训练速度）",
    "Training Grounds": "训练场地",
    "You focus the energy carefully, unlocking a steady flow of vitality. (+Energy regeneration for 5 minutes)": "你小心地集中精力，释放出源源不断的活力。（+ 5分钟能量回复）",
    "You focus your mind and reflect on the journey. (Gained some experience)": "你集中注意力，思考这段旅程。（获得了一些经验）",
    "Your respectful refusal earns the sage’s admiration. (+1 Charisma)": "你恭敬的拒绝赢得了圣人的赞赏。(+ 1魅力)",
    "Mediating the duel is exhausting. (-Energy regeneration for 5 minutes)": "调解这场决斗令人筋疲力尽。（-能量回复5分钟）",
    "The altar remains silent, and your gold vanishes.": "祭坛沉默了，你的金子消失了。",
    "In your rush to escape, you trip and fall. (-10% HP)": "在你急于逃跑的时候，你被绊倒了。（-10%生命）",
    "The apparition misleads you, wasting your time. (-Knowledge gain for 5 minutes)": "幽灵误导了你，浪费了你的时间。（-知识获取5分钟）",
    "The priest’s blessing fills you with resilience. (+1 Recovery)": "牧师的祝福让你充满了韧性。（+1恢复）",
    "You gain 25 gold. As you brush off the dirt, you notice intricate carvings on the coin’s surface. It seems ancient and valuable, almost as if it has seen centuries of trade.": "你获得了25个金币。当你刷掉污垢时，你会注意到金币表面上错综复杂的雕刻。它看起来古老而珍贵，似乎经历了几个世纪的贸易。",
    "A beautifully ornate mirror lies shattered on the ground. A strange aura surrounds it. You sense a powerful presence that could grant you untold power... at a cost.": "一面华丽的镜子摔碎在地上。一种奇怪的光环围绕着它。你感觉到一个强大的存在，可以给你无限的力量……这是有代价的。",
    "Join the Argument": "加入争论",
    "Mediate Between Them": "在他们之间进行调解",
    "Speaking passionately takes its toll on you. (-100% Energy)": "热情地讲话会让你付出代价。（-100%能量）",
    "The heated debate sharpens your understanding. (+Knowledge gain for 5 minutes)": "激烈的辩论能提高你的理解力。（+ 5分钟知识增益）",
    "The mirror binds to your soul, granting you increased stamina. (+1 Stamina, -50% energy regeneration for 5 minutes)": "魔镜绑定你的灵魂，增加你的耐力。（体力+1，能量回复-50%，持续5分钟）",
    "Touch the Mirror": "触摸镜子",
    "Two rival mages are arguing loudly in the market square over the correct incantation for a complex spell. The argument draws a crowd, and you are pulled into the fray.": "两个敌对的法师在市场广场上大声争论一个复杂法术的正确法术。争论吸引了一群人，你也被卷入其中。",
    "This rustic wooden rack is woven with strands of enchanted twine, used by skilled herbalists to preserve the potency of rare plants. Hanging bunches of herbs and roots sway gently, their fragrance filling the room and infusing the air with traces of ancient magic. With this rack, even common plants yield their highest quality, providing you a greater chance to find potent herbs in the wild.": "这个质朴的木架是用魔法线编织而成的，由熟练的草药师用来保存稀有植物的效力。一束束悬挂的草药和根茎轻轻摇曳，它们的香味充满了房间，在空气中注入了古老魔法的痕迹。有了这个架子，即使是普通的植物也能生产出最高质量的植物，为你提供了更大的机会在野外找到有效的草药。",
    "The Artisans Guild is a sanctuary of creativity and innovation, where members craft exquisite items and enhance their own bodies through artful modifications and enchanted designs. From intricate jewelry to empowered prosthetics, they blend beauty and functionality in everything they create. This guild embodies the pursuit of perfection in both craft and self-expression.": "工匠公会是一个充满创造力和创新的圣地，会员们在这里制作精美的物品，并通过巧妙的修改和魔法设计来增强自己的身体。从复杂的珠宝到强大的假肢，他们创造的每样东西都融合了美和功能。这个协会体现了对工艺和自我表达的完美追求。",
    "Workshop": "作坊",
    "A scroll inscribed with glowing runes that impart knowledge to the reader. It continuously generates insight, aiding the bearer in gradually increasing their understanding and intelligence over time.": "刻有发光的符文的卷轴，向读者传授知识。它不断地产生洞察力，帮助持有者随着时间的推移逐渐增加他们的理解和智力。",
    "% due to missing": "% 由于缺失造成",
    "A delicately folded paper charm shaped like a bird, imbued with restorative magic": "一个精致的折叠纸符咒形状像一只鸟，充满了恢复魔法",
    "A strange librarian approaches you with a cryptic riddle, promising a reward if you solve it.": "一个陌生的图书管理员带着一个神秘的谜语走近你，承诺如果你解开了就会得到奖励。",
    "Abandon Guild": "放弃公会",
    "Accessories": "配饰",
    "accessory": "配饰",
    "Alchemy": "炼金术",
    "Alchemy Efforts:": "炼金术的努力:",
    "Alchemy Slots:": "炼金术槽:",
    "Amnesia Potion": "失忆药水",
    "Aromatic Carpet": "芳香的地毯",
    "Artisans Guild": "工匠公会",
    "Ask for a Hint": "请求提示",
    "Attempt to Solve It": "尝试解决它",
    "Azureblossom": "Azureblossom",
    "Become member of young scientists community.": "成为青年科学家社区的一员。",
    "Build a machine that helps you to process wood": "制造一台机器来帮助你加工木材",
    "Cast a spell on your face to appear more friendly to others": "在你的脸上施一个法术，让你看起来对别人更友好",
    "Cauldron": "大锅",
    "Charm of Restoration Magic": "复原魔法的魅力",
    "Chemistry Lab": "化学实验室",
    "Craft aromatic carpet that inspires you and boosts your energy recovery": "制作芳香地毯，激发你的灵感，促进你的能量恢复",
    "Craft better and more reliable iron containers for storing coins": "制作更好和更可靠的铁制容器来储存金币",
    "Craft Enchanted magical paper scrolls": "制作魔法纸卷轴",
    "Craft Herbal Fibers": "制作草本纤维",
    "Craft Iron Plate": "制作铁板",
    "Craft Paper": "牛皮纸",
    "Craft Refined Wood": "精加工木材",
    "Craft Small Endurance Flask": "制作小耐久瓶",
    "Craft Small Experience Potion": "制造小经验药水",
    "Craft Small Healing Potion": "制作小型治疗药水",
    "craftable": "可制造",
    "Crafting": "制作",
    "Crafting Efficiency": "制作效率",
    "Crafting Efforts:": "制作工作量：",
    "Crafting Slots:": "制作插槽：",
    "Crafting Table": "制作桌",
    "Create an duplicated hammer. Of course, its just an imagination, but still it chops wood nice.": "创建一个重复的锤子。当然，这只是一种想象，但它仍然可以很好地劈木头。",
    "Create compact and easy to handle wooden caskets to improve your coins storage": "创建紧凑和易于处理的木盒，以提高您的金币存储",
    "Create ruby pendant that empowers your physical learning rate": "创建红宝石吊坠，赋予你的物理学习速度",
    "Create wooden talisman that holds information about your bio-rhythms and improve your health regeneration": "创造一个木头护身符，保存你的生物节律信息，提高你的生命回复",
    "Demolish": "拆除",
    "Device that capturing acoustic and energetic waves from your spells, and provide you waves histogram for further analysis and learning": "从你的法术中捕捉声波和能量波的装置，并为你提供波的直方图，以便进一步分析和学习",
    "Devote some space for platations to grow your very own herbs and plants": "留出一些空间种植你自己的草药和植物",
    "Dig well to make watering process more efficient, increasing plants growth rate": "挖井，使浇水过程更有效，提高植物的生长速度",
    "Dry and weave your herbs in fibers for further usage": "将草药干燥并编织成纤维以备以后使用",
    "Effects lasting:": "效果持久:",
    "Efficient Work Ethic": "高效的职业道德",
    "Ember Leaf": "余烬叶",
    "Enchant Paper": "附魔纸",
    "Enchanted Paper": "魔法纸",
    "Enhance your income from all sources, ensuring a steady flow of wealth": "增加你的收入来源，确保财富的稳定流动",
    "Enter merchants guild to become better in understanding how to earn and invest your coins.": "进入商人公会，更好地了解如何赚取和投资你的金币。",
    "Fertilizing Station": "施肥站",
    "Forget your previously learned skills, feel yourself refreshed. Of course, it will have consequences": "忘记你以前学过的技能，感觉自己焕然一新。当然，这是有后果的",
    "Golden Streams": "金色溪流",
    "Grow Aloe Vera": "种植芦荟",
    "Grow Berries": "种植浆果",
    "Grow Ember Leaf": "种植余烬叶",
    "Grow Fly Mushroom": "种植蝇菇",
    "Grow Ginseng": "种植人参",
    "Grow Harmony Blossom": "种植和谐之花",
    "Grow Mystic Bloom": "种植神秘之花",
    "Grow Nightshade": "种植龙葵",
    "Grow some aloe vera": "种植一些芦荟",
    "Grow some ginseng": "种植一些人参",
    "Grow some nightshade": "种植一些龙葵",
    "Guilds": "公会",
    "Harmony Blossom": "和谐之花",
    "Heartroot": "心根",
    "Herbal Fibers": "植物纤维",
    "Herbalist's Drying Rack": "中草药干燥架",
    "Herbalists Guild": "中医公会",
    "Herbs Plantation": "香草种植园",
    "Illusory Hammer": "虚幻的锤",
    "Improve the learning speed for work-related actions, maximizing your productivity": "提高与工作相关的学习速度，最大限度地提高你的生产力",
    "Increase your HP and energy caps": "增加你的生命值和能量上限",
    "Increase your mana cap": "增加你的魔法上限",
    "Increase your spell XP gain": "增加你的法术经验值",
    "Increasing level will increase spells cost and consumption but also increase their output": "等级的增加会增加法术的消耗和消耗，同时也会增加它们的输出",
    "Iron Ore": "铁矿石",
    "Iron Plate": "铁板",
    "Iron Stash": "铁罐",
    "Ironvine": "铁藤",
    "Jobs Learning Rate": "工作学习率",
    "Just plant some berries... OK?": "只要种些浆果……好吗?",
    "Learn merchants codex to be more efficient in selling your goods": "学习商人法典，以更有效地销售您的商品",
    "Lumber Mill": "锯木厂",
    "Mages Guild": "法师协会",
    "Magic book containing a lot of mental power": "魔法书里有很多精神力量",
    "Magic spirit captured into crystal provides significant amplifier to your magical capabilities": "魔法精神捕获到水晶提供了显着的放大器，你的魔法能力",
    "Mask of Friendliness": "友善的面具",
    "Master’s Table": "主人的表",
    "Mental Training Rate": "心理训练率",
    "Mentalist's Tome": "算命者的多美",
    "Merchants Codex": "商人法典",
    "Merchants Guild": "商人行会",
    "Mindroot": "心根",
    "Mindspire": "思维尖塔",
    "Minimalistic and very convenient bookcase can significantly increase amount of books you can store, and therefore increase your knowledge cap": "简约且非常方便的书柜可以大大增加你可以存储的书籍数量，从而增加你的知识上限",
    "Mystic Bloom": "神秘之花",
    "Occultist's Tome": "术士的典籍",
    "of": "of",
    "Paper": "纸",
    "Permanent Effects:": "永久性的影响:",
    "Place some additional equipment to improve your ability of studying chemical reactions between ingredients": "放置一些额外的设备来提高你研究成分之间化学反应的能力",
    "Plantation Slots:": "种植槽:",
    "Plantations": "种植园",
    "Plantations Efficiency": "种植园的效率",
    "Provides additional space for alchemy, revealing new alchemy slot": "提供额外的空间炼金术，揭示新的炼金术槽",
    "Provides additional space for crafting, revealing new crafting slot": "为锻造提供额外的空间，揭示新的锻造槽",
    "Purchase some basic tools for analyzing soil on your plantations and further increase your plantations efficiency": "购买一些基本的工具来分析你的种植园的土壤，进一步提高你的种植园效率",
    "rare": "稀有",
    "Reach": "达到",
    "Reach reputation level": "达到声誉等级",
    "Refine Ruby": "精炼红宝石",
    "Refine Sapphire": "精炼蓝宝石",
    "Refine wood and use it for your needs, or just sell it": "精炼木材，满足你的需要，或者直接卖掉",
    "Refine your stones to obtain trace amounts of rubies": "提炼你的宝石，以获得微量的红宝石",
    "Refine your stones to obtain trace amounts of sapphires": "提炼你的宝石以获得微量的蓝宝石",
    "Refined Wood": "精制木",
    "reputation level to increase your bonuses": "声誉等级来增加你的奖励",
    "Reputation Level:": "声誉等级：",
    "Reputation Points:": "声誉点：",
    "Reputation Progress:": "声誉进度:",
    "Reveal new alchemy opportunities by entering cauldron masters community.": "进入大锅大师社区，揭示新的炼金术机会。",
    "Right click + CTRL to consume": "右击+ CTRL以消耗",
    "Right click + SHIFT to consume all": "右键单击+ SHIFT以消耗所有",
    "Ruby": "红宝石",
    "Ruby Pendant": "红宝石垂饰",
    "Sapphire": "蓝宝石",
    "Sapphire Pendant": "蓝宝石吊坠",
    "Sapphire Ring": "蓝宝石戒指",
    "Scholars Guild": "学者协会",
    "Scroll of Wisdom": "智慧卷轴",
    "Set Effort:": "设置工作:",
    "Set level to": "设置等级为",
    "Small Endurance Flask": "小型耐久瓶",
    "Small Experience Potion": "小经验药水",
    "Small glowing tome. You feel inspiration every time you touch it": "小小的发光的书。每次触摸它，你都能感受到灵感",
    "Small Healing Potion": "小治疗药水",
    "Smelt iron ore into iron plates": "把铁矿石熔炼成铁板",
    "Social": "社会",
    "Social Training Rate": "社会培训率",
    "Specialized \"master’s table\" with enhanced tools that boosts crafting efficiency": "专门的“主人的桌子”与增强的工具，提高制作效率",
    "Spell Analyzer": "法术分析仪",
    "Spell XP Gain": "获得法术经验值",
    "Spirit Crystal": "精神水晶",
    "Spiritual Learning Rate": "精神学习速率",
    "Stone": "石头",
    "The librarian rewards you with a small pouch of coins.": "图书管理员奖励你一小袋金币。",
    "The riddle challenges your mind, enhancing your memory. (+1 Memory)": "谜语挑战你的思维，增强你的记忆力。(+ 1记忆)",
    "They say you are druggie, but never mind — you are a mage.": "他们说你吸毒，但没关系，你是个魔法师。",
    "This activity running at": "此活动运行于",
    "Tier": "层级",
    "Titanleaf": "泰坦之叶",
    "to unlock": "解锁",
    "True": "是",
    "Upgrade": "升级",
    "Use experimental and dangerous herbs at your risk in searching for better understanding of human and mages being": "为了更好地理解人类和魔法的存在，你要冒着风险使用实验和危险的草药",
    "Use healing herbs concentrate to save yourself from falling deceased": "使用治疗草药浓缩液使自己免于死亡",
    "Use your herbs to create more efficient substance to boost your energy": "使用草药来创造更有效的物质来增强你的能量",
    "Verdant Coil": "翠绿的线圈",
    "Vitality Talisman": "活力的护身符",
    "Well": "水井",
    "Wooden Bookcase": "木质书柜",
    "Wooden Casket": "木制棺材",
    "Wooden Talisman": "木制的护身符",
    "Workshop": "作坊",
    "You can select only one guild. But you can change it anytime you want.": "你只能选择一个公会。但是你可以随时改变它。",
    "You wont receive any new bonuses": "你不会得到任何新的奖励",
    "This practice demands immense concentration and endurance as you stand on a board embedded with nails. Through this rigorous discipline, you strengthen both mind and body, enhancing your efficiency in routine tasks.": "当你站在嵌有钉子的木板上时，这种练习需要极大的专注力和耐力。通过这种严格的纪律，你的身心都得到了加强，提高了你在日常工作中的效率。",
    "Engage with the public through speeches, events, and social interactions to inspire others and strengthen your influence. This action enhances the effectiveness of all social actions, making your efforts more impactful.": "通过演讲、活动和社会互动与公众接触，激励他人，增强你的影响力。这一行动提高了所有社会行动的有效性，使您的努力更有影响力。",
    "Read magic book, providing you precious information about increasing your magic potential. Unfortunately, the text inside is encrypted with runes that you have to de-crypt using spells.": "阅读魔法书，为你提供关于提高你的魔法潜力的宝贵信息。不幸的是，里面的文字是用符文加密的，你必须用法术解密。",
    "Finally you achieved that point where your brain allows you to understand the nature of magic. Analyze magic, mana and how its used by spells. Its hard and exhausting task, but totally worth it": "最终你的大脑会让你理解魔法的本质。分析魔法，魔法和它是如何被法术使用的。这是一项艰苦而累人的任务，但完全值得",
    "ETA:": "ETA:",
    "Academic Discussions": "学术讨论",
    "Advanced Craft": "高级工艺",
    "Basic Craft": "基本工艺",
    "Builder": "构建器",
    "Charitable Deeds": "慈善的行为",
    "Contribute your time and effort to support guild initiatives, earning reputation and respect.": "贡献你的时间和精力来支持公会的倡议，赢得声誉和尊重。",
    "crafting": "制作",
    "Dedicate your time and efforts to crafting": "把你的时间和精力花在制作上",
    "Dedicate yourself to helping others selflessly, sacrificing energy and health, but gaining patience and a boost to your charisma in return.": "奉献自己，无私地帮助他人，牺牲精力和健康，但获得耐心和提升你的魅力作为回报。",
    "Deliver an inspiring speech to guild members, boosting their morale and strengthening your reputation within the guild.": "向公会成员发表鼓舞人心的演讲，鼓舞他们的士气，提高你在公会中的声誉。",
    "Dig underground vaults to store your coins. Its energy consuming action, but can pay off": "挖掘地下金库来储存你的金币。它消耗能量的行动，却能得到回报",
    "Dig Vaults": "挖地窖",
    "During practice in the market square, your spell misfires, creating a harmless but embarrassing illusion of yourself.": "在集市广场练习时，你的咒语走火了，造成了一个无害但尴尬的假象。",
    "Engage in a deep meditative practice with the Metaphysics Book, sharpening memory and enhancing mana regeneration by channeling profound knowledge and magical focus.": "用这本形而上学的书进行深入的冥想练习，通过引导深刻的知识和魔法的专注来增强记忆和法力再生。",
    "Go to mine and get some iron ore": "到矿上取些铁矿石来",
    "Guild Donations": "协会捐款",
    "Guild Speech": "协会的演讲",
    "Guild Volunteering": "协会志愿者",
    "guild-activity": "公会活动",
    "Improve your magic capability using practices of ancient monks": "通过古代僧侣的练习来提高你的魔法能力",
    "Laugh It Off": "一笑了之",
    "Mages Reputation": "法师的声誉",
    "Magic Analysis": "魔法分析",
    "Magic Capabilty": "魔法容量",
    "Magic Training": "魔术培训",
    "Meditative Insight": "冥想的洞察力",
    "Merchants Reputation": "商家的声誉",
    "Mining": "采矿",
    "Nail Standing": "钉架",
    "Offer monetary support to the guild, boosting your reputation and helping fund its endeavors.": "向公会提供金钱支持，提高你的声誉并帮助其努力。",
    "Participate in thought-provoking academic discussions and debates to broaden your knowledge and understanding.": "参加发人深省的学术讨论和辩论，以扩大你的知识和理解。",
    "Public Engagement": "公众参与",
    "Quarrying": "采石",
    "Quickly Correct the Spell": "快速纠正咒语",
    "Rare Herbs": "罕见的药草",
    "Read Appretience Handbook": "阅读学徒手册",
    "Scholars Reputation": "学者的声誉",
    "Searching in Mages Backyard": "在法师后院搜索",
    "Searching in Silent Fields": "在寂静的田野里寻找",
    "Spell Reading": "法术解读",
    "Spend more time and efforts on crafting advanced things": "花更多的时间和精力制作高级的东西",
    "Spend some time trying to hear the magic inside you. Improve your feeling of yourself": "花点时间倾听你内心的魔力。改善你的自我感觉",
    "Spent some time brewing potions": "花了些时间熬药水",
    "Spent time walking through local market and talking to local merchants.": "花时间逛当地市场，和当地商人交谈。",
    "Spiritual Alignment": "精神上的一致性",
    "TBD": "TBD",
    "The artifact vanishes as soon as you touch it. Nothing happens.": "藏物一接触就会消失。什么也不会发生。",
    "The crowd finds your antics amusing and tosses some coins your way. (Refilled 10% of your coins storage)": "人群发现你的滑稽行动很有趣，并向你扔金币。（重新填充10%的金币存储）",
    "There is abandoned mages hut at the edge of settlement. It is told to be very dangerous, but having a lot of unique plants": "在定居点的边缘有一个废弃的法师小屋。据说那里非常危险，但有很多独特的植物",
    "Train Bargaining": "火车讨价还价",
    "Train Stamina": "耐力训练",
    "Work as builder. Its hard job, but well paid": "以建造者的身份工作。这份工作很辛苦，但薪水很高",
    "Work hard in quarry trying to find some rocks containing precious minerals": "在采石场努力工作，试图找到一些含有珍贵矿物的岩石",
    "Your improved endurance has unlocked a harder but much more efficient way to train your stamina": "耐力的提高开启了一种更困难但更有效的训练耐力的方式",
    "Mana Instability": "法力不稳定",
    "The altar rejects your prayer, sapping your energy. (-20% energy)": "祭坛拒绝你的祈祷，耗尽你的精力。（-20%能量）",
    "The correction drains your mana. (-Mana regeneration for 5 minutes)": "修正会消耗你的法力。（-法力回复5分钟）",
    "The sage’s wisdom broadens your understanding. (+Knowledge gain for 5 minutes)": "智者的智慧拓宽了你的理解力。（+ 5分钟知识增益）",
    "You can get reputation by performing jobs for your guilds": "你可以通过为公会执行任务而获得声誉",
    "Your mana regeneration is decreased": "你的法力回复降低",
    "A cloaked figure approaches you in the dark, offering a strange vial. \"Drink this,\" they say. \"It will change your life.\"": "一个披着斗篷的人在黑暗中走近你，递给你一个奇怪的小瓶子。“喝这个，”他们说。“它会改变你的生活。”",
    "Drink the Vial": "喝下小瓶",
    "Take the Vial but Don’t Drink It": "拿着小瓶，但不要喝",
    "The duel invigorates your magical energy. (+Mana regeneration for 5 minutes)": "决斗激发了你的魔法能量。（+法力回复5分钟）",
    "The liquid seems to do nothing at all.": "这种液体似乎什么作用也没有。",
    "The sage demonstrates a technique to replenish your mana. (+Mana regeneration for 5 minutes)": "圣人示范了一种技能来补充你的法力。（+法力回复5分钟）",
    "Your efforts to mediate help you understand complex spell interactions. (+Knowledge gain for 5 minutes)": "你对调解的努力帮助你理解复杂的咒语相互作用。（+ 5分钟知识增益）",
    "Improves your mana capacity": "提升法力容量",
    "Improves your spell learning rate": "提高你的法术学习速率",
    "/ Cast": "/ 施放",
    "Learn more sophisticated and rare herbs": "学习更多复杂和稀有的草药",
    "Paper Working": "纸张加工",
    "Random Events Bonus": "随机事件奖励",
    "The hint confuses you further. (-Knowledge gain for 5 minutes)": "这个提示让你更加困惑。（-知识获取5分钟）",
    "Unlocks new resource": "解锁新资源",
    "A mysterious fortune teller beckons you over, promising insights into your future for a price.": "一个神秘的算命先生向你招手，承诺对你的未来有深刻的见解。",
    "Her predictions are vague and unhelpful.": "她的预测含糊不清，毫无帮助。",
    "Pay for a Reading": "为阅读付费",
    "The fortune teller’s words inspire confidence in you. (+1 Charisma)": "算命先生的话激发了你的信心。(+ 1魅力)",
    "The text is confusing and gives you a headache. (-Knowledge gain for 5 minutes)": "这篇文章让人困惑，让人头疼。（-知识获取5分钟）",
    "Contains useful information regarding ancient civilizations languages.": "包含有关古代文明和语言的有用信息。",
    "Meditation Book": "冥想之书",
    "Learn how to meditate to increase your magic abilities.": "学习如何冥想来提高你的魔法能力。",
    "Purchase bigger storeroom to store your goods": "购买更大的储藏室来存放你的货物",
    "Storeroom": "储藏室",
    "Alchemy Courses": "炼金术课程",
    "Learn how to create useful potions from your herbs and other ingredients": "学习如何用草药和其他成分制作有用的药剂",
    "Magic Training Book": "魔法训练书",
    "Reveal the secrets of magic flowing through your body by learning new practices of training your magic capability": "通过学习训练你的魔术能力的新做法，揭示魔术流经你身体的秘密",
    "Spiritualism Book": "招魂之书",
    "Unlocks way to improve your spiritual activities by consuming magic knowledge. Also, unlocks new furniture": "通过消耗魔法知识来提高你的精神活动。同时，解锁新家具",
    "You push your limits and learn efficiently. (+1 Memory)": "你挑战自己的极限，高效地学习。(+ 1记忆)",
    "Boost your energy regeneration rate, ensuring you stay active for longer periods.": "提高你的能量再生速度，确保你在更长的时间里保持活跃。",
    "Crafting Expertise": "制作技能",
    "Endless Energy": "无尽的能量",
    "Enhance the efficiency of crafting actions, allowing you to create items with greater precision and speed.": "提高制作行动的效率，让你以更高的精度和速度创造物品。",
    "Increase your health regeneration, keeping you in peak condition during challenging tasks.": "增加你的生命回复，使你在挑战性任务中保持最佳状态。",
    "Vital Recovery": "生命恢复",
    "Accelerate learning speed for routine tasks, making them less time-consuming": "加快日常任务的学习速度，减少学习时间",
    "Enhance the learning speed of mental actions, sharpening your intellect": "提高心理活动的学习速度，磨砺你的智力",
    "Increase the amount of knowledge you gain from intellectual pursuits.": "增加你从智力追求中获得的知识。",
    "Knowledge Seeker": "知识探索者",
    "Mental Acumen": "精神敏锐",
    "Routine Mastery": "常规精通",
    "The shrine remains silent, and your gold disappears into the void.": "神殿保持沉默，你的金子消失在虚空中。",
    "Arcane Expertise": "奥术专长",
    "Boost the experience gained from casting spells, mastering the art of magic": "提升施法经验，掌握魔法艺术",
    "Expand your maximum mana reserves, enabling more powerful spells.": "扩大你的最大法力储备，启用更强大的法术。",
    "Increase the learning speed of spiritual actions, strengthening your magical prowess": "提高精神行动的学习速度，增强你的魔法能力",
    "Mana Well": "法力井",
    "Spiritual Enlightenment": "精神启蒙",
    "Alchemical Mastery": "炼金术精通",
    "Boost the output of plantations, ensuring richer harvests of valuable plants": "提高种植园的产量，确保有价值的植物获得更丰富的收成",
    "Effortless Routine": "轻松的日常",
    "Green Fingers": "园艺技能",
    "Improve the learning speed of routine tasks, making them second nature": "提高日常任务的学习速度，使之成为第二天性",
    "Increase the efficiency of the 'Alchemy' action, creating more potent results": "提高“炼金术”行动的效率，创造更有效的结果",
    "The hint broadens your understanding. (+Knowledge gain for 5 minutes)": "这个暗示拓宽了你的理解力。（+ 5分钟知识增益）",
    "exact": "精确",
    "Loading": "加载中",
    "Careful Gathering": "小心收集",
    "description": "描述",
    "exact": "精确的",
    "Exploration Efforts:": "探索工作：",
    "Gathering Effort": "收集工作",
    "Gathering Equipment": "采集装备",
    "Herbs Gathered": "采集的草药",
    "Join Discord": "加入Discord",
    "Loading": "加载中",
    "Low Rarity Gather Prob.": "低稀有性收集问题",
    "Map": "地图",
    "Purchase Basic Gathering equipment to increase probability of finding regular items and herbs": "购买基本收集装备，增加找到常规物品和草药的概率",
    "Search in:": "搜索范围：",
    "Spend some time looking for items, but without many risks": "花些时间寻找物品，但不要冒太多风险",
    "Support Me": "支持我",
    "Tags": "标签",
    "The surge overwhelms you! Energy leaks from your body, leaving you weaker. (Lost all your energy)": "潮水淹没了你！能量从你的身体中泄漏出来，让你变得更虚弱。（失去了所有的精力）",
    "World": "世界",
    "You endure the pain and emerge stronger. (+1 Strength, -50% HP)": "你忍受痛苦，变得更坚强。（+1力量，-50%生命值）",
    "When you hover over action card, in right panel you can see details of your action. There is most of important information, such as action level (see #2 on the picture above) and effects/resources that this action can provide to you when running or on level up": "当你将鼠标悬停在行动卡上时，在右侧面板中你可以看到你的行动细节。这是最重要的信息，如行动级别（参见上图中的第2点）以及该行动在跑步或升级时可以提供给你的效果/资源",
    "If you check the Efficiency stat, you’ll see how your loot probability and quantity are affected by a lack of Gathering Effort. However, as you continue exploring, your gathering action will level up, improving your efficiency over time.": "如果你查看了效率属性，你便会发现你的战利品概率和数量会因为缺乏收集努力而受到影响。然而，当你继续探索，你的收集行动将升级，提高你的效率随着时间的推移。",
    "In general, actions can be divided onto 2 categories: Actions, giving you some resources while you working on them (like \"Beggar\" job), and actions providing passive bonuses per each level (like \"Walking\")": "一般来说，行动可以分为两类：行动，在你工作时给予你一些资源（如“乞丐”工作），以及行动，在每个关卡提供被动奖励（如“行走”）。",
    "Map exploration is a feature unlocked when you purchase the backpack upgrade, which allows you to hold, use, and trade items. It lets you spend time searching for various collectible items.": "地图探索是当你购买背包升级后解锁的功能，它允许你持有、使用和交易物品。它让你花时间寻找各种可收集的物品。",
    "Some actions require resources to run. For example, \"Begging\" requires energy. If you dont have enough energy to sustain your begging - it will run at reduced efficiency. For example, if your action require 0.5 energy per second, but you produce only 0.2 - your total energy balance will be negative (-0.3). Once your energy hits 0 - your action will be able to consume only 0.2 energy per second that you produce, so it will run at 40% efficiency (0.2/0.5)": "有些行动需要资源才能运行。例如，“乞讨”需要能量。如果你没有足够的能量来维持你的乞讨——它会以低效率运行。例如，如果你的行动每秒需要0.5能量，但你只产生0.2能量，那么你的总能量平衡将是负的（-0.3）。一旦你的能量达到0 -你的行动将能够消耗0.2能量每秒产生，所以它将以40%的效率运行（0.2/0.5）",
    "Specific items and herbs available on a tile are randomly generated and remain hidden until you discover the first item of that type. For example, you won’t know that berries exist in a forest until you find one.": "特定的道具和草药是随机生成的，并且会一直隐藏，直到你发现第一个此类道具。例如，在你找到浆果之前，你不会知道森林里有浆果。",
    "This is your map view. At the top of the page (#1 in the image), you can see your available/used Gathering Effort. If you don’t have enough, your exploration efficiency will decrease.": "这是你的地图视图。在页面的顶部（图中的#1），你可以看到你可用的/使用的收集成果。如果你没有足够的资源，你的探索效率就会下降。",
    "For your information - game is working on background. So, you can select action and switch to different tab safely (while having game tab opened in background) - once you return you'll get your rewards for running the action.": "给你的信息-游戏正在后台工作。所以，你可以选择行动并安全地切换到不同的标签（同时在后台打开游戏标签）-一旦你返回，你将获得运行行动的奖励。",
    "Below your exploration stats is the map itself. The map is divided into 225 tiles (15x15). The central tile is your settlement, and it cannot be explored. You can click any other tile (#2) to view its details.": "在你的探索数据下方是地图本身。地图被分成225块（15x15）。中央瓦片是你的定居点，它不能被探索。你可以点击任何其他平铺（#2）来查看它的详细信息。",
    "To start exploring the map, you need to run (or add to a list) an action that generates \"Gathering Effort.\" Gathering Effort is the resource used to explore different tiles on the map.": "要开始探索地图，您需要运行（或添加到列表中）生成“收集努力”的操作。“收集精力是用来探索地图上不同贴图的资源。",
    "Actions are tasks that your personage performs over time to receive resources or improve himself": "行动是你的人物在一段时间内为获得资源或提高自己而执行的任务",
    "Almost every action has it's level, that will be increased automatically once you run action and received enough XP in it. Action bonuses are depending on its level.": "几乎每个行动都有自己的等级，当你执行行动并获得足够的经验值时，等级会自动提高。行动奖励取决于它的等级。",
    "Another important factor to consider is efficiency.": "另一个需要考虑的重要因素是效率。",
    "gatherable": "可采集",
    "Happy exploring!": "探索快乐!",
    "herb": "草药",
    "How actions works?": "行动是如何起作用的？",
    "How it works?": "它是如何工作的？",
    "Like other areas of the game, map exploration can also be automated. Check out the \"Lists\" and \"Automations\" tutorials for more details, as the mechanics are similar here.": "与游戏的其他领域一样，地图探索也可以实现自动化。查看“列表”和“自动化”教程了解更多细节，因为这里的机制是相似的。",
    "Map Exploration": "地图探索",
    "The farther a tile is from the center, the higher its exploration cost. However, more loot can be found there, and with better probabilities.": "离中心越远的瓦片，其勘探成本越高。然而，在那里可以找到更多的战利品，而且概率更高。",
    "To run some action - just click \"Start\" button (#1 on the screen above). From this point action will run, and give you some resources or bonuses": "要运行一些操作-只需点击“开始”按钮（屏幕上的#1）。从这一点行动将运行，并给你一些资源或奖励",
    "The apparition shares a secret, permanently enhancing your memory. (+1 Memory)": "幽灵分享一个秘密，永久增强你的记忆力。(+1记忆)",
    "The merchant smirks and disappears into the crowd. You lose some of your coins.": "商人得意地笑了笑，消失在人群中。你丢了一些金币。",
    "The water was tainted, and you feel drained. (-50% energy)": "水被污染了，你感到筋疲力尽。(-50%的能量)",
    "A simple yet potent concoction brewed from golden algae and knowledge moss. Consuming it grants a one-time surge in experience.": "用金藻和知识苔藓酿造的简单而有力的混合物。消耗它可以获得一次经验值的激增。",
    "An efficient tool that automates the process of buying upgrades in the shop.": "一个有效的工具，自动购买升级的过程在商店。",
    "Armchair": "扶手椅",
    "Basin Bowl": "盆碗",
    "Charisma Price Discount": "魅力价格折扣",
    "Click on craft recipes to add/remove them from the list": "点击工艺食谱添加/删除它们从列表中",
    "Click on tiles to add/remove them from the list": "点击瓷砖，从列表中添加或删除它们",
    "Craft Insight Potion": "工艺洞察药水",
    "General Stats": "一般的统计数据",
    "Golden Algae": "金色的藻类",
    "Harvest Vision": "丰收愿景",
    "Hover over specific item to see it details": "将鼠标悬停在特定项目上以查看其详细信息",
    "Insight Potion": "顿悟药水",
    "Knowledge Moss": "知识苔藓",
    "Looking quite oddly, but comfortable": "看起来很奇怪，但很舒服",
    "No map recipes added yet": "还没有添加地图配方",
    "No map tiles added yet": "还没有添加地图贴图",
    "Price Discount Multiplier": "价格折扣乘数",
    "Purchase Manager": "采购经理",
    "Sell Stock Renew Rate": "卖出股票续期率",
    "Shop Max Sell Stock": "商店最大销售库存",
    "Temporarily enhances the caster's ability to locate valuable resources on the map. A glowing aura sharpens perception, increasing the likelihood of discovery.": "暂时增强施法者在地图上定位有价值资源的能力。一个发光的光环使人的感知更加敏锐，增加了发现的可能性。",
    "A rare alignment of celestial bodies fills the air with arcane energy. A mysterious portal appears before you, pulsating with power.": "罕见的天体排列使空气中充满了神秘的能量。一个神秘的传送门出现在你面前，充满了力量。",
    "Approach the Pedestal": "接近基座",
    "Arcane Convergence": "奥术收敛",
    "Catalog the Library’s Contents": "为图书馆的内容编目",
    "Close the Portal": "关闭传送门",
    "Observe from a Distance": "从远处观察",
    "Step Into the Portal": "进入传送门",
    "Study the Ancient Texts": "学习古代文献",
    "The altar accepts your offering, bestowing vitality upon you. (+Health regeneration for 5 minutes)": "坛悦纳你的供物，赐你活力。（+生命回复5分钟）",
    "The altar grants a small boon, increasing your health regeneration temporarily. (+Health regen for 5 minutes)": "圣坛给予你一个小恩赐，暂时提高你的生命回复。（+生命回复5分钟）",
    "The effort drains your mana reserves. (-Mana regeneration for 5 minutes)": "此努力消耗你的法力储备。（法力恢复5分钟）",
    "The Forgotten Archive": "被遗忘的档案",
    "The monk disappears after taking your gold. You gain nothing.": "和尚拿走你的金子后就消失了。你什么也得不到。",
    "The monk shares his wisdom, and you feel your mind expand. Your learning rate temporarily increased": "和尚和你分享他的智慧，你会觉得自己的思想开阔了。你的学习率暂时提高了",
    "The portal destabilizes, sapping your vitality. (-Health regeneration for 5 minutes)": "传送门不稳定，耗尽你的活力。（-生命回复5分钟）",
    "You discover a hidden library filled with ancient texts. A glowing pedestal at its center beckons you forward.": "你发现了一个隐藏的图书馆，里面装满了古代文献。在它的中心一个发光的基座召唤你前进。",
    "Your prayer is answered, and you feel an inner strength awaken. (+1 Recovery)": "你的祈祷得到了回应，你感到内心的力量被唤醒。（+1恢复）",
    "The log contains dangerous warnings that unsettle you. (-10% HP)": "日志中包含让你不安的危险警告。（-10%生命）",
    "You learn useful details from the log. (+Knowledge gain for 5 minutes)": "您可以从日志中了解有用的细节。（+ 5分钟知识增益）",
    "Patience impacts on your ability on focusing on routine tasks, increasing their learning speed. Higher level unlocks more gathering and routine activities": "耐心会影响你专注于日常任务的能力，提高他们的学习速度。等级越高可以解锁更多的聚会和日常活动",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "mental_magic": "精神魔法",
    "material": "材料",
    "routine": "常规",
    "inventory": "库存",
    "consumable": "可消耗",
    "social": "社会",
    "politician": "政治家",
    "mental": "精神",
    "rest": "休息",
    "upgrade": "升级",
    "shop": "商店",
    "purchaseable": "可购买",
    "job": "工作",
    "physical": "体力",
    "action": "行动",
    "training": "训练",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "v0.0.6a": "v0.0.6a",
    "NaN": "NaN",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Gather Berries: ": "采集浆果: ",
    "Train Math: ": "训练数学: ",
    "Street Musician: ": "街头音乐家: ",
    "Read book of Math: ": "阅读数学之书: ",
    "Read book of Motivation: ": "阅读励志之书: ",
    "Gossip: ": "闲聊: ",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Locked ": "未解锁 ",
    "Primary Attribute: ": "主属性: ",
    "Walking: ": "散步: ",
    "Beggar: ": "乞讨: ",
    "Train Endurance: ": "训练耐力: ",
    "Rest in Tavern: ": "在酒馆休息: ",
    "Visit City: ": "访问城市: ",
    "Push Up: ": "俯卧撑: ",
    "Clean Stable: ": "清理马厩: ",
    "You can use this time to speed up your game by factor of ": "你可以利用这段时间来加快游戏速度 ",
    "You have lifted an item in position ": "你把一件东西举起来了在位置 ",
    "Mana selected, ": "选择的法力，",
    "Learn Anatomy: ": "学习解剖学: ",
    "Read Books: ": "读书: ",
    "Rest at home: ": "在家休息: ",
    "Learn Languages: ": "学习语言: ",
    "Home Errands: ": "家庭杂务: ",
    "Running Action, ": "运行行动，",
    "Running Action With Tag, ": "运行行动带标签，",
    "Resource Amount selected, ": "选择的资源数量，",
    "Resource Balance, ": "资源平衡，",
    "Yoga Practice: ": "瑜伽练习: ",
    "Meditate: ": "冥想: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " to full": " 填满",
    " to empty": " 耗完",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)d ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\/([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^\+([\d\.]+)M$/,
    /^\+([\d\.]+)T$/,
    /^\+([\d\.]+)B$/,
    /^\-([\d\.]+)K$/,
    /^\-([\d\.]+)M$/,
    /^\-([\d\.]+)B$/,
    /^\-([\d\.]+)T$/,
    /^X([\d\.]+)K$/,
    /^X([\d\.]+)M$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^X([\d\.]+)$/,
    /^\/([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) minutes$/, '$1 分钟'],
    [/^([\d\.,]+) minute$/, '$1 分钟'],
    [/^([\d\.,]+) hour$/, '$1 小时'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) results available.$/, '$1 结果可用。'],
    [/^You have dropped the item.\n      \n      You have moved the item from position ([\d\.,]+)\n      to position ([\d\.,]+)\n    $/, '你拖到并放置了行动项.\n      \n      你移动了行动项从位置 $1\n      到位置 $2\n    '],
    [/^The item has been dropped while not over a drop area.\n    \n  The item has returned to its starting position\n  of ([\d\.,]+)\n$/, '行动项没有被拖到指定放置区域。\n \n该行动项目已返回到其起始位置\n $1\n）'],
    [/^You have moved the item from position ([\d\.,]+)\n      to position ([\d\.,]+)$/, '您已将行动项从位置 $1 \n移动到位置 $2'],
    [/^\(Reach ([\d\.,]+) coins\)$/, '(达到 $1 金币)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);